### PR TITLE
rfilter.h: Include <limits>

### PR DESCRIPTION
**Pull request by tbaederr**
This file uses `std::numeric_limits`, so should include the standard <limits> header.

## Description

Fixes # (issue)

## Checklist

- [ ] My code follows the [style guidelines](https://mitsuba.readthedocs.io/en/latest/src/developer_guide.html#coding-style) of this project
- [ ] My changes generate no new warnings
- [ ] My code also compiles for `cuda_*` and `llvm_*` variants. If you can't test this, please leave below
- [ ] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I cleaned the commit history and removed any "Merge" commits
- [ ] I give permission that the Mitsuba 3 project may redistribute my contributions under the terms of its [license](https://github.com/mitsuba-renderer/mitsuba/blob/master/LICENSE)

### CODE REVIEW

**Comment by Speierers** [comment]
Is this necessary though? If your compiler complains I would be curious to know which compiler it is (and the version).

**Comment by tbaederr** [comment]
This is necessary when using libstdc++, after applying https://github.com/mitsuba-renderer/nanogui/pull/130 as well.

**Comment by Speierers** [comment]
When using Clang, Mitsuba should be compiled using `libc++` instead of `libstdc++`. Does the compilation succeed and the test suite run if you compile with `libstdc++` using your patch?

**Comment by tbaederr** [comment]
> When using Clang, Mitsuba should be compiled using `libc++` instead of `libstdc++`.

I know. What i don't know is why that limitation exists.

> Does the compilation succeed and the test suite run if you compile with `libstdc++` using your patch?

The compilation succeeds. I am unfamiliar with pytest, so not sure how to properly run the test suite.  [The documentation](https://mitsuba2.readthedocs.io/en/latest/src/developer_guide/testing.html) just mentions invoking `pytest`, but that that just throws a `ModuleNotFoundError: No module named 'drjit'`.

**Comment by Speierers** [comment]
you will need to run `source setpath.sh` first in order to set the Mitsuba and Dr.Jit PATH first. Then simply execute `python3 -m pytest ../src` from the `build` directory.

**Comment by tbaederr** [comment]
Thanks for the instructions, that worked. I don't have a cuda-capable GPU so the tests using cuda all failed. However, both when using libstdc++ and libc++, 447 tests failed and 1413 tests succeeded (with `-m no slow`).

**Comment by Speierers** [comment]
Okay I can merge this as it is a minor change.

**Pull request merged**
