### PR TITLE
Differential `to_world` camera parameter

### PR DESCRIPTION
**Pull request by Speierers**
## Description

This PR attempts to enable the differentiation of the `perspective` and `thinlens` camera `to_world` parameter for camera pose estimation.

**WIP: currently changes in this PR produce wrong / biased gradients**

### CODE REVIEW

**Comment by satyajitghana** [comment]
```
SceneParameters[
  -------------------------------------------------------------------------------------------
  Name                                    Flags    Type            Parent
  -------------------------------------------------------------------------------------------
  PerspectiveCamera.near_clip                      float           PerspectiveCamera
  PerspectiveCamera.far_clip                       float           PerspectiveCamera
  PerspectiveCamera.shutter_open                   float           PerspectiveCamera
  PerspectiveCamera.shutter_open_time              float           PerspectiveCamera
  PerspectiveCamera.film.size                      ScalarVector2u  HDRFilm
  PerspectiveCamera.film.crop_size                 ScalarVector2u  HDRFilm
  PerspectiveCamera.film.crop_offset               ScalarPoint2u   HDRFilm
  PerspectiveCamera.x_fov                          Float           PerspectiveCamera
  PerspectiveCamera.to_world                       Transform4f     PerspectiveCamera
  mat-MyMaterial.005.reflectance.value    ∂        Color3f         SRGBReflectanceSpectrum
  PointLight.position                              Point3f         PointLight
  PointLight.intensity.value              ∂        Color3f         SRGBReflectanceSpectrum
  OBJMesh.bsdf.reflectance.value          ∂        Float           UniformSpectrum
  OBJMesh.vertex_count                             int             OBJMesh
  OBJMesh.face_count                               int             OBJMesh
  OBJMesh.faces                                    UInt            OBJMesh
  OBJMesh.vertex_positions                ∂, D     Float           OBJMesh
  OBJMesh.vertex_normals                  ∂, D     Float           OBJMesh
  OBJMesh.vertex_texcoords                ∂        Float           OBJMesh
]
```

Hi, I've installed mitsuba from source, but still the `to_world` paramter doesn't seem to be differentiable. it doesn't have the `∂` flag

**Comment by satyajitghana** [comment]
Nevermind, i did a clean build and it's fine now

```
>>> print(params)
SceneParameters[
  -------------------------------------------------------------------------------------------
  Name                                    Flags    Type            Parent
  -------------------------------------------------------------------------------------------
  PerspectiveCamera.near_clip                      float           PerspectiveCamera
  PerspectiveCamera.far_clip                       float           PerspectiveCamera
  PerspectiveCamera.shutter_open                   float           PerspectiveCamera
  PerspectiveCamera.shutter_open_time              float           PerspectiveCamera
  PerspectiveCamera.film.size                      ScalarVector2u  HDRFilm
  PerspectiveCamera.film.crop_size                 ScalarVector2u  HDRFilm
  PerspectiveCamera.film.crop_offset               ScalarPoint2u   HDRFilm
  PerspectiveCamera.x_fov                 ∂, D     Float           PerspectiveCamera
  PerspectiveCamera.to_world              ∂, D     Transform4f     PerspectiveCamera
  mat-MyMaterial.005.reflectance.value    ∂        Color3f         SRGBReflectanceSpectrum
  PointLight.position                              Point3f         PointLight
  PointLight.intensity.value              ∂        Color3f         SRGBReflectanceSpectrum
  OBJMesh.bsdf.reflectance.value          ∂        Float           UniformSpectrum
  OBJMesh.vertex_count                             int             OBJMesh
  OBJMesh.face_count                               int             OBJMesh
  OBJMesh.faces                                    UInt            OBJMesh
  OBJMesh.vertex_positions                ∂, D     Float           OBJMesh
  OBJMesh.vertex_normals                  ∂, D     Float           OBJMesh
  OBJMesh.vertex_texcoords                ∂        Float           OBJMesh
]
>>>
```

**Comment by satyajitghana** [comment]
```
key = 'PerspectiveCamera.to_world'
```

```
opt = mi.ad.Adam(lr=0.05)
opt[key] = params[key]
params.update(opt);
```

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In [58], line 2
      1 opt = mi.ad.Adam(lr=0.05)
----> 2 opt[key] = params[key]
      3 params.update(opt);

File ~/miniconda3/envs/pytorch3d/lib/python3.9/site-packages/mitsuba/python/ad/optimizers.py:51, in Optimizer.__setitem__(self, key, value)
     39 """
     40 Overwrite the value of a parameter.
     41 
   (...)
     48 and calling `reset()` is advisable.
     49 """
     50 if not (dr.is_diff_v(value) and dr.is_float_v(value)):
---> 51     raise Exception('Optimizer.__setitem__(): value should be differentiable!')
     52 needs_reset = (key not in self.variables) or dr.shape(self.variables[key]) != dr.shape(value)
     54 self.variables[key] = dr.detach(value, True)

Exception: Optimizer.__setitem__(): value should be differentiable!
```

```
dr.is_diff_v(params[key])
```

```
False
```


I am not sure why i am getting False, `to_world` should be differentiable

**Comment by jenyav94** [comment]
Have the same error. The actual master branch is built, `sensor.to_world` is declared as differentiable in print output, but in fact  `dr.is_diff_v(params['sensor.to_world'])` is `False`

```
SceneParameters[
  ----------------------------------------------------------------------
  Name               Flags    Type  Parent
  ----------------------------------------------------------------------
  sensor.to_world    ∂, D     Transform4f PerspectiveCamera
]

```
I checked `src/integrators/tests/test_ad_integrators.py`, tests passed, but `sensor.to_world` remains non differentiable. Tests doesn't fail because `theta` forwarded which is actually differentiable. And the error is below the threshold because `theta` is zero and `sensor.to_world` does not change.

**Comment by Speierers** [comment]
It is currently impossible to directly optimize the values of a `mi.Transform4f`.  In any case, optimizing both the underlying matrix values and its `inverse_transpose` separately will generate incorrect matrices. For this reason, we recommend optimizing latent variables instead that are then used to create a transform (e.g. like done in the tutorials).

**Pull request merged**
